# Generated by Django 5.2.8 on 2025-11-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gameproject_post_rename_game_gamecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/movie-cover/%Y/%m/%d/')),
                ('is_opensource', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='GameCategory',
            new_name='Game',
        ),
        migrations.DeleteModel(
            name='GameProject',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='movie_id',
            new_name='game_id',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
