# Generated by Django 5.2.8 on 2025-11-24 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_project_rename_gamecategory_game_delete_gameproject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desc',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
