# Generated by Django 5.2.8 on 2025-12-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_desc_post_body_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='embed_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
