# Generated by Django 5.2.8 on 2026-01-30 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_project_desc_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('sender', models.CharField(blank=True, max_length=50, null=True)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('color', models.CharField(default='#feff9c', max_length=7)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_reply', models.TextField(blank=True, max_length=500, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
