# Generated by Django 5.2.8 on 2026-08-03 13:01

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_note_color_alter_project_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(default='FAVORITES', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='game',
            name='hero_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='last_played',
            field=models.CharField(default='Yesterday', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='playtime_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.PositiveIntegerField(default=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='game',
            name='review_content',
            field=models.TextField(blank=True, help_text='Telegra.ph style markdown/HTML review text with images & GIFs', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='review_headline',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_appid',
            field=models.IntegerField(blank=True, help_text='Steam App ID for automated Steam assets', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
