# Generated by Django 5.2.8 on 2026-08-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_game_category_game_cover_url_game_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(default='STEAM', max_length=20),
        ),
    ]
