# Generated by Django 5.2.8 on 2026-08-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_game_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='store_url',
            field=models.URLField(blank=True, help_text='Link to game store page', max_length=500, null=True),
        ),
    ]
