# Generated by Django 5.2.8 on 2026-08-19 09:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_game_store_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('author', models.CharField(default='Abbos Jabborov', max_length=100)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/stories/%Y/%m/%d/')),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(help_text='Notion / Telegra.ph style markdown or rich content with image/gif URLs')),
                ('tags', models.CharField(blank=True, default='Article', max_length=200)),
                ('reading_time', models.CharField(blank=True, default='3 min read', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SphereNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Node title displayed in 3D sphere', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='Short description or tagline', max_length=200, null=True)),
                ('category', models.CharField(choices=[('PROJECT', 'Project'), ('STORY', 'Story / Article'), ('GAME', 'Game'), ('SOCIAL', 'Social / Contact'), ('EXPERIMENT', 'Experiment / Demo'), ('OTHER', 'Other')], default='PROJECT', max_length=20)),
                ('node_type', models.CharField(choices=[('EXTERNAL', 'External Link'), ('STORY', 'Internal Story / Notion Reader')], default='EXTERNAL', max_length=20)),
                ('url', models.URLField(blank=True, help_text='Target URL for external links (e.g. scrolls.claive.uz)', max_length=500, null=True)),
                ('custom_slug', models.SlugField(blank=True, help_text='Slug for routing if node_type is STORY', null=True)),
                ('color', models.CharField(default='#00f0ff', help_text='Hex color or theme for node glow', max_length=20)),
                ('icon', models.CharField(default='globe', help_text='Icon identifier (e.g. globe, book, gamepad, code, user)', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('story', models.ForeignKey(blank=True, help_text='Linked story if node_type is STORY', null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.story')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
